openapi: 3.0.1
info:
  title: Text Summarization
  description: |+
    This NLP microservice takes in any given input text blurb and generates a summary of up to a maximum of 168 words.

    The input text should be a minimum of 100 words and a maximum of 512 words. 

    For longer text, we suggest breaking them up into smaller chunks and making multiple calls to this microservice for more effective summarization.
  version: '0.2.0'
  x-subscribelink: text_summarization
  x-apitype: Large file
  x-apitypedescription: |+
    Asyncronous | Batch | 10GB/File
  x-inputfilelimit: |+
    Process up to 10000 kb of data or chat per API call.
  x-responsetime: |+
    The response rate is slower than the small file API due to large data
  x-billingmethod: |+
    The API is billed by the amount of data transferred.
  x-notes: |+
    Size cannot exceed more than 512 words.
servers:
  - url: 'https://dev-apis.sentient.io'
tags:
  - name: v0.2.0
    description: 'Published Date - Aug 11, 2021'
paths:
  /async/microservices/nlp/textsummarisation/v0/getuploadurl:
    post:
      tags:
        - v0.2.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                results:
                  fields:
                    content-type: text/plain
                    key: >-
                      1/2/lp-textsummarisation/input/test_1991d4936ddb4728afaa06cb260b0253.txt
                    policy: >-
                      eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW50LVR5cGUiLCJ0ZXh0L3BsYWluIl0sWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwxMjMyOTM2XSx7ImNvbnRlbnQtdHlwZSI6InRleHQvcGxhaW4ifSx7IngtZ29vZy1tZXRhLWFkZGl0aW9uYWxfcGFyYW0iOiJOb25lIn0seyJ4LWdvb2ctbWV0YS1vaWQiOiIxIn0seyJ4LWdvb2ctbWV0YS11aWQiOiIyIn0seyJ4LWdvb2ctbWV0YS11dWlkIjoiMTk5MWQ0OTM2ZGRiNDcyOGFmYWEwNmNiMjYwYjAyNTMifSx7ImJ1Y2tldCI6InVzZXJfc3BhY2VfZGV2In0seyJrZXkiOiIxLzIvbHAtdGV4dHN1bW1hcmlzYXRpb24vaW5wdXQvdGVzdF8xOTkxZDQ5MzZkZGI0NzI4YWZhYTA2Y2IyNjBiMDI1My50eHQifSx7IngtZ29vZy1kYXRlIjoiMjAyMTExMjNUMTA1ODQ2WiJ9LHsieC1nb29nLWNyZWRlbnRpYWwiOiJzZW50aWVudC1kZXYtYmlncXVlcnlAc2VudGllbnQtMjA3MzEwLmlhbS5nc2VydmljZWFjY291bnQuY29tLzIwMjExMTIzL2F1dG8vc3RvcmFnZS9nb29nNF9yZXF1ZXN0In0seyJ4LWdvb2ctYWxnb3JpdGhtIjoiR09PRzQtUlNBLVNIQTI1NiJ9XSwiZXhwaXJhdGlvbiI6IjIwMjEtMTEtMjNUMTE6NTg6NDYuMTcxMzE1WiJ9
                    x-goog-algorithm: GOOG4-RSA-SHA256
                    x-goog-credential: >-
                      sentient-dev-bigquery@sentient-207310.iam.gserviceaccount.com/20211123/auto/storage/goog4_request
                    x-goog-date: 20211123T105846Z
                    x-goog-meta-additional_param: None
                    x-goog-meta-oid: '1'
                    x-goog-meta-uid: '2'
                    x-goog-meta-uuid: 1991d4936ddb4728afaa06cb260b0253
                    x-goog-signature: >-
                      3d882f0762743e39146aae926435bf0b15e844836db9a0913fddfc04e786b939a8f3d1bcf187883c3c1dec913d1aa8eca4e8e08d7a8fcdf138bfac621f28ed9ef30c842b6a7ad9c7b7fa8a0ee60d4f1b05f7a0322a5bb404d7ce69410a494b1a5848d49ac96cd59c538dc522b21e579979b5d53b9d413e766662f65596ca22bde2f625d349392c04e13ce27d98e0d73a229f50dfc5fdb18873218f97eac6e83a8d088c6c66e49d120d21757d04ab5763565da5594eeafd31d5cc1e68f0f5933f8b2f517db16fa962be6f9c59fc5564fc909fe226c14dddbfdfd1bfc46aa21b72aec3db576b34e73cfb7acfdbca8d5cb14da998fe5c0b7f050c3656bb1d6d6052
                  jid: 1991d4936ddb4728afaa06cb260b0253
                  request_cost: 0
                  url: 'https://storage.googleapis.com/user_space_dev/'
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
  /async/microservices/voice/asr/v0/getstatus:
    get:
      tags:
        - v0.2.0
      parameters:
        - in: query
          name: jid
          schema:
            type: string
          example: 36d075917dcd481e9daf858a2549f3b1
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getsuccess'
              example:
                last_updated: 'July 06, 2021'
                message: File Processing Successfully Started
                request_cost: 0.086
                status: Processing
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
components:
  schemas:
    getsuccess:
      type: object
      properties:
        last_updated:
          type: string
          example: July 06, 2021
          description: Last updated
        message:
          type: string
          example: File Processing Successfully Started
          description: Detail description on the API status
        request_cost:
          type: string
          example: 0.086
          description: Detail description on the API status
        status:
          type: string
          example: Processing
          description: Detail description on the API status
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        results:
          type: object
          example:
            <Json: Object>
          description: Json Object of returned results
          properties:
            fields:
              type: object
              example:
                <Json: Object>
              description: Json Object of returned results
              properties:
                content-type:
                  type: string
                  example: text/plain
                  description: Content type of the document
                policy:
                  type: string
                  example: eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW50LVR5cGUiLCJ...
                  description: Content type of the document
                x-goog-algorithm:
                  type: string
                  example: GOOG4-RSA-SHA256
                  description: Google algorithm
                x-goog-credential:
                  type: string
                  example: sentient-dev-bigqu...
                  description: Google algorithm
                x-goog-date:
                  type: string
                  example: 20211123T105846Z
                  description: Google algorithm
                x-goog-meta-additional_param:
                  type: string
                  example: None
                  description: Google algorithm
                x-goog-meta-oid:
                  type: string
                  example: 1
                  description: Google algorithm
                x-goog-meta-uid:
                  type: string
                  example: 2
                  description: Google algorithm
                x-goog-meta-uuid:
                  type: string
                  example: 1991d4936ddb4728afaa06cb260b0253
                  description: Google algorithm
                x-goog-signature:
                  type: string
                  example: 3d882f0762743e39146aae926435bf0b15e844836dbcf...
                  description: Google algorithm
            jid:
              type: string
              example: 1991d4936ddb4728afaa06cb260b0253...
              description: Google algorithm
            request_cost:
              type: string
              example: 0
              description: Google algorithm
            url:
              type: string
              example: 'https://storage.googleapis.com/user_space_dev/'
              description: Google algorithm
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid input - Error in URL.
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v0.2.0:
          type: array
          items:
            oneOf:
              - type: string
                example: 'Published Date - Aug 11, 2021'
                x-details: Model Upgrade
                description: Latest version
        v0.1.2:
          type: array
          items:
            oneOf:
              - type: string
                example: 'Published Date - Jun 07, 2021'
                x-details: Deeper Postprocessing of Summarised text
                description: Depreciating on Aug 10,2021
        v0.1.1:
          type: array
          items:
            oneOf:
              - type: string
                example: 'Published Date - May 12, 2021'
                x-details: Postprocessing of Summarised text
                description: Depreciating on Jun 06,2021
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: 'Published Date - Apr 07, 2021'
                x-details: Initial version release
                description: Archived
    input:
      type: object
      required:
        - file_name
      properties:
        file_size:
          x-name: file_size
          type: integer
          default: true
          example: 1227936
          description: |
            File Size
        file_name:
          x-name: file_name
          type: string
          default: true
          format: binary
          example: test.txt
          description: |
            File name
        content_type:
          x-name: content_type
          type: string
          default: true
          example: text/plain
          description: |
            Content type
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
