openapi: 3.0.1
info:
  title: User List
  description: Get user list
  x-subscribelink: user_list
  version: '1.0.0'
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io'
tags:
- name: "v1.0.0"
  description: "Published Date - May 21, 2021"
paths:
   /org/v0/getuserlist:
    get:
      tags:
        - v1.0.0
      parameters:
        - in: query
          name: org_id
          schema:
            type: integer
          description: Organization Id
          example: 1120
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: successfully processed
                results:
                  - created_by: admin
                    date_created: 01 oct 2020 / 20:45
                    groups:
                      - id: 1485
                        value: AI & Data (Individual)
                      - id: 1486
                        value: Data Alliance Basic Access
                    id: 1522
                    last_activity: ''
                    root_user: 'yes'
                    user_name: sritest1@gmail.com
                status: success
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: The detail description on the status
        results:
          type: array
          example: [{<JSON result Object}]
          description: The list of Json result object
          items:
            type: object
            properties:                      
                created_by:
                  type: string
                  description: User created by
                  example: "admin"
                date_created: 
                  type: string
                  description: User created date
                  example: "06 oct 2020 / 11:37"
                groups: 
                  type: array
                  example: [{<JSON ressnult Object}]
                  items:
                    type: object
                    properties:                      
                        id:
                          type: integer
                          description: Id of the user
                          example: "1491"
                        value:
                          type: string
                          description: Name of the user
                          example: "AI & Data (Individual)"
                id: 
                  type: string
                  description: Id of the user
                  example: "1527"
                last_activity: 
                  type: string
                  description: User last activity
                  example: "06 oct 2020 / 11:37"
                root_user: 
                  type: string
                  description: Root user
                  example: "yes"
                user_name: 
                  type: string
                  description: User name
                  example: "dev061020_v1@sent.io"
        status:
          type: string
          example: Success
          description: The status of the API call Success/Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Nov 25,2019
              description: Initial version release          
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
