openapi: 3.0.1
info:
  title: Rule Engine
  description: |+
    It is an expert-system program, which runs the rules on the data and if any condition matches then it executes the corresponding actions. The inference engine is the component of the intelligent system in artificial intelligence, which applies logical rules to the knowledge base to infer new information from known facts. Inference-Engine’s program works in three phases to execute the rule on given data, Match, Resolve and Execute. 
  version: '1.0.0'
  x-subscribelink: rule_engine
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 10MB/Call
  x-inputfilelimit: |+
    Process up to 10MB of data per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    File size cannot exceed 10 MB.
  x-apidetailsdesc: |+
     Sentient’s Rule-Engine uses the Rete Algorithm for pattern matching. It is one of the best algorithms for pattern matching.
servers:
  - url: 'https://dev-apis.sentient.io/ruleengine/microservices/dataanalytics'
tags:
- name: "v1.0.0"
  description: "Published Date - Oct 30, 2020"
paths:
  /getsuggestion/v0/getresults:
    post:
      tags:
        - v1.0.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: 
                message: Successfully Processed
                status: Success
                results:
                  suggestion: Please begin by choosing Create/Modify Global parts on screen or Create/Modify
                    Global parts by download/upload master. Alternatively, you can request support
                    here[link to chatbot].
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
      
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          description: The message of the API call.
          example: Successfully Processed
        status:
          type: string
          description: The status of the API call.
          example: Success
        results:
          type: object
          properties:
            suggestion:
              type: string
              description: The message of the API call.
              example: Please begin by choosing Create/Modify Global parts on screen or Create/Modify Global parts by download/upload master. Alternatively, you can request support here[link to chatbot].
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v1.0.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Oct 30, 2020
                x-details: Standardizing Output JSON
                description: Latest Version
    input:
      type: object
      properties:
        page_url:
          type: string
          default: true
          description: |+ 
            Page URL of getting suggestion
          example: https://test.brivge.com/globalparts/create
        time_interval:
          type: number
          default: true
          description: |+ 
            Time interval of getting suggestion value will be greater than or equal to 60000
          example: 60000
        selected_mode:
          type: string
          description: |+ 
             Default value null. Selected mode of getting suggestion
          example: Create/Modify Global parts on screen
        upload:
          type: number
          description: |+ 
             Default value 0. Upload of getting suggestion value will be greater than 0
          example: 1
        add_item:
          type: number
          description: |+ 
             Default value 0. Add Item of getting suggestion value will be greater than 0
          example: 1
        edit_item:
          type: number
          description: |+ 
             Default value 0. Edit item of getting suggestion value will be greater than 0
          example: 1
        first_prompt:
          type: string
          description: |+ 
             Default value false.First prompt of getting suggestion value will be true/false
          example: true
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
         
