openapi: 3.0.1
info:
  title: ASR with Voice Activity Detection ENG
  description: |+
    This Voice microservice combines Voice Activity Detection feature and Automatic Speech Recognition capability. It detects speech in an audio file (.wav format) and transcribes English speech content from the audio stream into text. The transcript text is timestamped for each utterance. An utterance is a continuous piece of speech beginning and ending with a clear pause.
    
    This Voice microservice performs well on Singapore-accented English speech. For best performance, select the model which best matches the use-case: news_parliament, nsc_parliament, nscfull_8k.
    
    The length of your audio should be **upto 60 seconds**. 

    For longer audio, we suggest breaking them up into smaller chunks and making multiple calls to this microservice for more effective transcription.
  version: '0.1.0'
  x-additionalinfo: |+
    Suggested Use Cases:
    - Combine this with the Text-to-Speech API to deliver voice-enabled experiences in IoT (Internet of Things) applications, such as implementing voice commands like “turn the volume up".
  x-subscribelink: asr_with_voice_activity_detection_eng
  x-apitype: large file
  x-apitypedescription: |+
    Asyncronous | Batch | 10GB/File
  x-inputfilelimit: |+
    Process up to 10000 kb of data or chat per API call.
  x-responsetime: |+
    The response rate is slower than the small file API due to large data
  x-billingmethod: |+
    The API is billed by the amount of data transferred.
  x-notes: |+
    Size cannot exceed 60 seconds.
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v0.1.0"
  description: "Published Date - Nov 09, 2021"
paths:
  /async/microservices/voice/vadasr/v0/getuploadurl:
    description: |+
      Upload your file to start processing
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                results:
                  fields:
                    content-type: audio/mpeg
                    key: >-
                      309/495/lp-vadasr/input/113test_7c949f4a2cdd4cfc87de9a66cbe53eea.mp3
                    policy: >-
                      eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW50LVR5cGUiLCJhdWRpby9tcGVnIl0sWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwxMTMzNzgyMDVdLHsiY29udGVudC10eXBlIjoiYXVkaW8vbXBlZyJ9LHsieC1nb29nLW1ldGEtYWRkaXRpb25hbF9wYXJhbSI6Ik5vbmUifSx7IngtZ29vZy1tZXRhLW9pZCI6IjMwOSJ9LHsieC1nb29nLW1ldGEtdWlkIjoiNDk1In0seyJ4LWdvb2ctbWV0YS11cGxvYWRlciI6IjBiYjczMzliMGM0ZTQ3NmM5YjY0NzVlMDkwMzRlMjMzIn0seyJ4LWdvb2ctbWV0YS11dWlkIjoiN2M5NDlmNGEyY2RkNGNmYzg3ZGU5YTY2Y2JlNTNlZWEifSx7ImJ1Y2tldCI6InVzZXJfc3BhY2VfZGV2In0seyJrZXkiOiIzMDkvNDk1L2xwLXZhZGFzci9pbnB1dC8xMTN0ZXN0XzdjOTQ5ZjRhMmNkZDRjZmM4N2RlOWE2NmNiZTUzZWVhLm1wMyJ9LHsieC1nb29nLWRhdGUiOiIyMDIxMTIxN1QwNTQ0MjNaIn0seyJ4LWdvb2ctY3JlZGVudGlhbCI6InNlbnRpZW50LWRldi1iaWdxdWVyeUBzZW50aWVudC0yMDczMTAuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20vMjAyMTEyMTcvYXV0by9zdG9yYWdlL2dvb2c0X3JlcXVlc3QifSx7IngtZ29vZy1hbGdvcml0aG0iOiJHT09HNC1SU0EtU0hBMjU2In1dLCJleHBpcmF0aW9uIjoiMjAyMS0xMi0xN1QwNjo0NDoyMy4yODUyMjRaIn0=
                    x-goog-algorithm: GOOG4-RSA-SHA256
                    x-goog-credential: >-
                      sentient-dev-bigquery@sentient-207310.iam.gserviceaccount.com/20211217/auto/storage/goog4_request
                    x-goog-date: 20211217T054423Z
                    x-goog-meta-additional_param: None
                    x-goog-meta-oid: '309'
                    x-goog-meta-uid: '495'
                    x-goog-meta-uploader: '0bb7339b0c4e476c9b6475e09034e233'
                    x-goog-meta-uuid: 7c949f4a2cdd4cfc87de9a66cbe53eea
                    x-goog-signature: >-
                      9d5387492104addd79296abe2feb38bbe9947092de7f32c44e85d3844c0ac1c9dd2317102d7a36dd2e0eeea1944a5d689dc193dafce67958984fb25a20bd252bab0a930caeb7dd761028bae463860e795441ab69e0cc1bd937d135f889eb33e582228523ec77ece6fd1df7b29fa9cd02d54e0caaefccfc3cfe28f65682bc15ce78666b4ad094e42cf4c841e7556d378d34f7966b635272991071be64e5d39a132e7d2bce4e5d7d320a815c2f3dcbdab3b5cf78ee4be982ed1b75d0773e39c4326119e16ad999f8fef7e8892a57943b427cab0d2ff5593e1703bb6b62383c0a65ab11adba128e6f0c40d89e1ea6254116de932735c5464a2c6d941e7e456aee2c
                  jid: 7c949f4a2cdd4cfc87de9a66cbe53eea
                  request_cost: 7.9361
                  url: 'https://storage.googleapis.com/user_space_dev/'
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
  /async/microservices/voice/vadasr/v0/getstatus:
    description: |+
      Query for processing status
    get:
      tags:
        - v0.1.0
      parameters:
        - in: query
          name: jid
          schema:
            type: string
          example: 36d075917dcd481e9daf858a2549f3b1
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getsuccess'
              example:
                last_updated: 'Dec 17, 2021'
                message: Successfully Processed
                output_url: https://storage.googleapis.com/user_space_dev/309/495/lp-peoplecounting/output/415KB_e7fe34e9c21c4d75bc94051e476141c5.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=sentient-dev-bigquery%40sentient-207310.iam.gserviceaccount.com%2F20211217%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20211217T055955Z&X-Goog-Expires=86400&X-Goog-SignedHeaders=host&X-Goog-Signature=8b88cfac70c9b5402a97777fe630264ed493ec43607aaee434f51d4efda397262cb9f40f0f526a60c8633fd9b5dbc74307ad56f93455a617f401b98d233f53cdac0ab6488e962d2984df08811d57de5a99b53ddf7cb617df68f138df965f99bff5858e02f7c2270f13cd8f0d8a5499fad1736db6371c27f74942e95750b499dcbdc84df0a6f8abd4f43c6030d8daeb426e5b1dccb2abda5a43307caec0bb105d1b828a8749ab03edf7fb69915befd9147e345974d96d1d4c4814fe5edd3516e51c1401a935bd8599ecc297c4daf82e67d1e59b80f20432181815a37096e526fad1b0b7c198076a55fa92a653f7e9683a0feebbe78f2e7658938be9f6052e013e
                request_cost: 0.0298
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
components:
  schemas:
    getsuccess:
      type: object
      properties:
        last_updated:
          type: string
          example: Dec 17, 2021
          description: Last updated
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        request_cost:
          type: string
          example: 0.0298
          description: Detail description on the API status
        status:
          type: string
          example: Success
          description: Detail description on the API status
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        results:
          type: object
          example:
            <Json: Object>
          description: Json Object of returned results
          properties:
            fields:
              type: object
              example:
                <Json: Object>
              description: Json Object of returned results
              properties:
                content-type:
                  type: string
                  example: text/plain
                  description: Content type of the document
                policy:
                  type: string
                  example: eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW50LVR5cGUiLCJ...
                  description: Content type of the document
                x-goog-algorithm:
                  type: string
                  example: GOOG4-RSA-SHA256
                  description: Google algorithm
                x-goog-credential:
                  type: string
                  example: sentient-dev-bigqu...
                  description: Google algorithm
                x-goog-date:
                  type: string
                  example: 20211217T054423Z
                  description: Google algorithm
                x-goog-meta-additional_param:
                  type: string
                  example: None
                  description: Google algorithm
                x-goog-meta-oid:
                  type: string
                  example: 309
                  description: Google algorithm
                x-goog-meta-uid:
                  type: string
                  example: 495
                  description: Google algorithm
                x-goog-meta-uploader:
                  type: string
                  example: 0bb7339b0c4e476c9b6475e09034e233
                  description: Google algorithm
                x-goog-meta-uuid:
                  type: string
                  example: 7c949f4a2cdd4cfc87de9a66cbe53eea
                  description: Google algorithm
                x-goog-signature:
                  type: string
                  example: 9d5387492104addd79296abe2feb38bbe9947092de7f32c44e85...
                  description: Google algorithm
            jid:
              type: string
              example: 7c949f4a2cdd4cfc87de9a66cbe53eea
              description: Google algorithm
            request_cost:
              type: string
              example: 7.9361
              description: Google algorithm
            url:
              type: string
              example: 'https://storage.googleapis.com/user_space_dev/'
              description: Google algorithm
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid input - Error in URL.
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v0.1.0:
          type: array
          items:
            oneOf:
            - type: string
              example: Published Date - Dec 17, 2021
              x-details: Initial version release
              description: Latest Version
    input:
      type: object
      required:
        - file_name
      properties:
        file_size:
          x-name: file_size
          type: integer
          default: true
          example: 1227936
          description: |
            File Size
        file_name:
          x-name: file_name
          type: string
          default: true
          format: binary
          example: test.mp3
          description: |
            File name
        content_type:
          x-name: content_type
          type: string
          default: true
          example: audio/mpeg
          description: |
            Content type
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
