
openapi: 3.0.1
info:
  title: Text-To-Speech ENG
  description: |+
        This Voice microservice converts English text into natural-sounding English speech in a female voice. 

        User can adjust the pitch and tempo of the the synthesised speech. Both are optional and used only for the female_singaporean model.

        The input text should not exceed **2000 characters**.
  version: 1.0.0
  x-subscribelink: text-to-speech_eng
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 3000 characters/Call
  x-inputfilelimit: |+
    Process up to 3000 characters of data per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    Limit cannot exceed 3000 characters.
  x-apidetailsdesc: |+
    Converts English text to speech in a female voice.
servers:
  - url: 'https://apis.sentient.io' 
tags:
- name: "v1.0.0"
  description: "Published Date - Jun 7, 2021"
paths:
  /microservices/voice/ttseng/ncsv0/getpredictions:
    post:
      tags:
        - v1.0.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                results: 
                  sampling_rate: 22050
                  wav_base64: Cuxz6/zqlupS6o/qL+vW66Dsle2e7tDv//AM8jfzbvR49WX2Off798/4k/
                  message: Successfully Processed
                  status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'       
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        results:
          type: object
          description: The result of the API call.
          example: { "<Json": "Object>" }
          properties: 
            sampling_rate:
              description: Sample rate of the output audio
              example: 22050
              type: integer
            wav_base64:
              description: Base64 string of the generated audio from input text
              example: Cuxz6/zqlupS6o/qL+vW66Dsle2e7tDv//AM8jfzbvR49WX2Off798/4k/
              type: string

        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
        
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v1.0.0:
          type: array
          items:
            oneOf:
              - type: string
                example: 'Published Date - Jun 7,2021'
                description: New model release - female_singaporean
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: 'Published Date - Sep 28,2018'
                description: Initial version release    
    input:
      type: object
      required:
      
        - text
        - model
      
      properties:
        text:
          x-name: text
          type: string
          default: True
          example: I want a credit card
          description: |+
            Input text to be synthesised 
        model:
          x-name: model
          type: string
          default: True
          example: female_singaporean
          description: |+
            Model selection. For best performance, select the model which best matches the use-case&#58;
          
            1. female_singaporean
        
        
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
