openapi: 3.0.1
info:
  title: People Counting (Large File)
  description: |+
    This Computer Vision microservice tracks and counts people appearing in the input video.
    
    This microservice returns the number of people detected in that video, the likelihood of overestimation/underestimation, the first appearance, the duration and confidence of each person detected.
    
    The size of your image file should **not exceed 10 MB**, and the image dimension should be **least more than 416x416 pixels**. 
    For larger image, we suggest breaking them up into smaller chunks and making multiple calls to this microservice for more effective appearance and confidence of each person detected.
  x-additionalinfo: |+
    Suggested Use Cases:
    - Improve visitor experience and optimize operations in retail, leisure, and other sectors - build services to count visitor traffic in venues, measure detailed movements and interactions, and visualize that data to better understand what is happening in within a certain spaces. For example, one can optimize traffic, staff and marketing strategies to increase conversion rates and profits with actionable data. Businesses can use visitor count as a benchmark to figure out the conversion rate for a certain spot to see the real performance. Efficiently allocating the number of staff according to hourly visitor traffic will also create value in terms of revenue, profit and efficiency.
  version: '0.1.0'
  x-subscribelink: people_counting_large_file
  x-apitype: large file
  x-apitypedescription: |+
    Asyncronous | Batch | 10GB/File
  x-inputfilelimit: |+
    Process up to 10000 kb of data or chat per API call.
  x-responsetime: |+
    The response rate is slower than the small file API due to large data
  x-billingmethod: |+
    The API is billed by the amount of data transferred.
  x-notes: |+
    Size of image file should not exceed 10 MB.
servers:
  - url: 'https://dev-apis.sentient.io'
tags:
- name: "v0.1.0"
  description: "Published Date - Aug 11, 2021"
paths:
  /async/microservices/cv/peoplecounting/v0/getuploadurl:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: 
                message: Successfully Processed
                results:
                  fields:
                    content-type: video/mp4
                    key: >-
                      309/495/lp-peoplecounting/input/415KB_e7fe34e9c21c4d75bc94051e476141c5.mp4
                    policy: >-
                      eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW50LVR5cGUiLCJ2aWRlby9tcDQiXSxbImNvbnRlbnQtbGVuZ3RoLXJhbmdlIiwwLDQzMDM5MV0seyJjb250ZW50LXR5cGUiOiJ2aWRlby9tcDQifSx7IngtZ29vZy1tZXRhLWFkZGl0aW9uYWxfcGFyYW0iOiJOb25lIn0seyJ4LWdvb2ctbWV0YS1vaWQiOiIzMDkifSx7IngtZ29vZy1tZXRhLXVpZCI6IjQ5NSJ9LHsieC1nb29nLW1ldGEtdXBsb2FkZXIiOiI0ZjIwNmIyN2Y2NWQ0ZWYyYjc4Zjg5NGQ5NjdiMmQzOSJ9LHsieC1nb29nLW1ldGEtdXVpZCI6ImU3ZmUzNGU5YzIxYzRkNzViYzk0MDUxZTQ3NjE0MWM1In0seyJidWNrZXQiOiJ1c2VyX3NwYWNlX2RldiJ9LHsia2V5IjoiMzA5LzQ5NS9scC1wZW9wbGVjb3VudGluZy9pbnB1dC80MTVLQl9lN2ZlMzRlOWMyMWM0ZDc1YmM5NDA1MWU0NzYxNDFjNS5tcDQifSx7IngtZ29vZy1kYXRlIjoiMjAyMTEyMTdUMDU0NzU4WiJ9LHsieC1nb29nLWNyZWRlbnRpYWwiOiJzZW50aWVudC1kZXYtYmlncXVlcnlAc2VudGllbnQtMjA3MzEwLmlhbS5nc2VydmljZWFjY291bnQuY29tLzIwMjExMjE3L2F1dG8vc3RvcmFnZS9nb29nNF9yZXF1ZXN0In0seyJ4LWdvb2ctYWxnb3JpdGhtIjoiR09PRzQtUlNBLVNIQTI1NiJ9XSwiZXhwaXJhdGlvbiI6IjIwMjEtMTItMTdUMDY6NDc6NTguNzU4NzkzWiJ9
                    x-goog-algorithm: GOOG4-RSA-SHA256
                    x-goog-credential: >-
                      sentient-dev-bigquery@sentient-207310.iam.gserviceaccount.com/20211217/auto/storage/goog4_request
                    x-goog-meta-additional_param: None
                    x-goog-meta-oid: '309'
                    x-goog-meta-uid: '495'
                    x-goog-meta-uploader: '4f206b27f65d4ef2b78f894d967b2d39'
                    x-goog-meta-uuid: e7fe34e9c21c4d75bc94051e476141c5
                    x-goog-signature: >-
                      79a52d6b4417e3505fdee766d4ccf4976cbd1f4f9507c986f0b476b8481d26d233002125339e7b39a958e2b200468eb6f9d64bbb56ccc59880f6db562425774aa79f7510c10d3cf575327e0c63ec4d5eb889c0cfdfa88f2f4f18a0ceffff737ade2985ac15f508eaf83f52e13fcbf87c93874f2031feca04f7ad38590ce2fbe75f16949d71b45ed9fbb80947f99e240cb282bc9890ebdcbbc0783d8d09cae8a3c1678e01c30a1bc911b1ef0b64b6aff9040de99d3b87419117449f4567d4926c7c73c9b90d1a52ed2e624bba6f2e8a212ed5fb46581b0f7dba42cd72b2c2cad1fa77fac2f7e2d50346ecd41528fc85e9030f550a90491f9a7c6bf5e44bd9fc34
                  jid: e7fe34e9c21c4d75bc94051e476141c5
                  request_cost: 0.0298
                  url: 'https://storage.googleapis.com/user_space_dev'
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
  /upload:
    post:
      servers:
        - url: 'https://storage.googleapis.com/user_space_dev/'
          description: Override base path for the GET /ping operation    
      tags:
        - v0.1.0
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadinput'
        required: true          
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: 
                message: Successfully Processed         
  /async/microservices/cv/peoplecounting/v0/getstatus:
    description: |+
      Query for processing status
    get:
      tags:
        - v0.1.0
      parameters:
        - in: query
          name: jid
          schema:
            type: string
          example: e7fe34e9c21c4d75bc94051e476141c5
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getsuccess'
              example:
                last_updated: 'Dec 17, 2021'
                message: Successfully Processed
                output_url: presigned URL
                request_cost: 0.0298
                status: Success

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
components:
  schemas:
    getsuccess:
      type: object
      properties:
        last_updated:
          type: string
          example: 2021-07-06 12:50:30
          description: Last updated
        message:
          type: string
          example: File Processing Successfully Started
          description: Detail description on the API status
        request_cost:
          type: string
          example: 0.086
          description: Detail description on the API status
        status:
          type: string
          example: Processing
          description: Detail description on the API status
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        results:
          type: object
          example: { "<Json": "Object>" }
          description: Json Object of returned results
          properties:   
            fields:
              type: object
              example: { "<Json": "Object>" }
              description: Json Object of returned results
              properties:
                content-type:
                  type: string
                  example: text/plain
                  description: Content type of the document
                policy:
                  type: string
                  example: eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW50LVR5cGUiLCJ...
                  description: Content type of the document
                x-goog-algorithm:
                  type: string
                  example: GOOG4-RSA-SHA256
                  description: Google algorithm
                x-goog-credential:
                  type: string
                  example: sentient-dev-bigqu...
                  description: Google algorithm
                x-goog-date:
                  type: string
                  description: Google algorithm
                x-goog-meta-additional_param:
                  type: string
                  example: None
                  description: Google algorithm
                x-goog-meta-oid:
                  type: string
                  example: 1
                  description: Google algorithm
                x-goog-meta-uid:
                  type: string
                  example: 2
                  description: Google algorithm
                x-goog-meta-uuid:
                  type: string
                  example: 1991d4936ddb4728afaa06cb260b0253
                  description: Google algorithm
                x-goog-signature:
                  type: string
                  example: 3d882f0762743e39146aae926435bf0b15e844836dbcf...
                  description: Google algorithm
            jid:
              type: string
              example: 1991d4936ddb4728afaa06cb260b0253...
              description: Google algorithm 
            request_cost:
              type: string
              example: 0
              description: Google algorithm 
            url:
              type: string
              example: https://storage.googleapis.com/user_space_dev/
              description: Google algorithm 
        status:
          type: string
          example: Success
          description: The status of the API call success/failure              
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid input - Error in URL.
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure 
    versions:
      type: object
      properties: 
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Dec 23, 2021
              x-details: Initial version release  
              description: Archived
    input:
      type: object
      required:
        - file_name
      properties:
        file_size:
          x-name: file_size
          type: integer
          default: true
          example: 1227936
          description: |+
            File Size
        file_name:
          x-name: file_name
          type: string
          default: true
          format: binary
          example: 'test.txt'
          description: |+
            File name
        content_type:
          x-name: content_type
          type: string
          default: true
          example: 'text/plain'
          description: |+
            Content type
    uploadinput:
      type: object
      required:
        - filePath      
      properties:
        filePath:
          type: string
          format: binary
          default: true
          example: sample.wav
          description: file
        content-type:
          type: string
          default: false
          example: application/pdf
          description: Fields
        key:
          type: string
          default: false
          example: 309/495/lp-peoplecounting/input/415KB_e7fe34e9c21c4d75bc94051e476141c5.mp4
          description: Fields
        policy:
          type: string
          default: false
          example: eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW50LVR5cGUiLCJ2aWRlby9tcDQiXSxbImNvbnRlbnQtbGVuZ3RoLXJhbmdlIiwwLDQzMDM5MV0seyJjb250ZW50LXR5cGUiOiJ2aWRlby9tcDQifSx7IngtZ29vZy1tZXRhLWFkZGl0aW9uYWxfcGFyYW0iOiJOb25lIn0seyJ4LWdvb2ctbWV0YS1vaWQiOiIzMDkifSx7IngtZ29vZy1tZXRhLXVpZCI6IjQ5NSJ9LHsieC1nb29nLW1ldGEtdXBsb2FkZXIiOiI0ZjIwNmIyN2Y2NWQ0ZWYyYjc4Zjg5NGQ5NjdiMmQzOSJ9LHsieC1nb29nLW1ldGEtdXVpZCI6ImU3ZmUzNGU5YzIxYzRkNzViYzk0MDUxZTQ3NjE0MWM1In0seyJidWNrZXQiOiJ1c2VyX3NwYWNlX2RldiJ9LHsia2V5IjoiMzA5LzQ5NS9scC1wZW9wbGVjb3VudGluZy9pbnB1dC80MTVLQl9lN2ZlMzRlOWMyMWM0ZDc1YmM5NDA1MWU0NzYxNDFjNS5tcDQifSx7IngtZ29vZy1kYXRlIjoiMjAyMTEyMTdUMDU0NzU4WiJ9LHsieC1nb29nLWNyZWRlbnRpYWwiOiJzZW50aWVudC1kZXYtYmlncXVlcnlAc2VudGllbnQtMjA3MzEwLmlhbS5nc2VydmljZWFjY291bnQuY29tLzIwMjExMjE3L2F1dG8vc3RvcmFnZS9nb29nNF9yZXF1ZXN0In0seyJ4LWdvb2ctYWxnb3JpdGhtIjoiR09PRzQtUlNBLVNIQTI1NiJ9XSwiZXhwaXJhdGlvbiI6IjIwMjEtMTItMTdUMDY6NDc6NTguNzU4NzkzWiJ9
          description: Fields
        x-goog-algorithm:
          type: string
          default: false
          example: GOOG4-RSA-SHA256
          description: Fields
        x-goog-date:
          type: string
          default: false
          description: Fields          
        x-goog-credential:
          type: string
          default: false
          example: sentient-dev-bigquery@sentient-207310.iam.gserviceaccount.com/20211209/auto/storage/goog4_request
          description: Fields
        x-goog-meta-additional_param:
          type: string
          default: false 
          description: Fields
        x-goog-meta-oid:
          type: string
          default: false
          example: 1
          description: Fields
        x-goog-meta-uid:
          type: string
          default: false
          example: 2
          description: Fields
        x-goog-meta-uuid:
          type: string
          default: false
          example: cf3d329bd9df4cef91966c336386eea3
          description: Fields
        x-goog-meta-uploader:
          type: string
          default: false
          example: cf3d329bd9df4cef91966c336386eea3
          description: Fields          
        x-goog-signature:
          type: string
          default: false
          example: 7970619677c2a0dc26af460a7d62f883528af9e1e8a1459aa09671ee0fbf15f7a611b7bd8c382fd8d39f74fe212a7e3db1768535f0c1ccff062239627ebe49195cc2c42c2238eb5e268ecaca49e647eb244eb023f3d4ba97922fd1228aab677a7176b9f84fef1c909897ccf0e1e8f9e3d030dbfc9892c7c026060dcf20b4ad4598f346de478b0f8495d9bce292b83a5b3bfa13c7dc08a2ce162f652c3bce91191167eeee3019b6b196e4271f5e3a6a1fe067f70acdaa082e6091c2f3ac8182bca8be41afc90600fc32dcdb3072acb43aaf90910a38c4aec9e3a42fdd21deb5ce936d8269e9ed011377ef058cac20d336218a35858753bd99b4ffdb1db171f0f4
          description: Fields            
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
